GPU available: False, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/home/tim/anaconda3/envs/JetNN/lib/python3.11/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:613: UserWarning: Checkpoint directory /home/tim/JetNN/jetnn/runners/wandb/run-20230706_161519-fgm5gwbe/files exists and is not empty.
  rank_zero_warn(f"Checkpoint directory {dirpath} exists and is not empty.")
  | Name     | Type                           | Params
------------------------------------------------------------
0 | _encoder | MethodNameMyTransformerEncoder | 51.0 M
1 | _decoder | MethodNameTransformerDecoder   | 85.2 M
2 | _metrics | MetricCollection               | 0
3 | _loss    | SequenceCrossEntropyLoss       | 0
------------------------------------------------------------
136 M     Trainable params
0         Non-trainable params
136 M     Total params
544.435   Total estimated model params size (MB)
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 19400/19400 [00:00<00:00, 353932.77it/s]
  0%|                                                                                                                                                                                                                                                 | 0/19400 [00:00<?, ?it/s]
/home/tim/anaconda3/envs/JetNN/lib/python3.11/site-packages/torch/nn/modules/transformer.py:296: UserWarning: The PyTorch API of nested tensors is in prototype stage and will change in the near future. (Triggered internally at ../aten/src/ATen/NestedTensorImpl.cpp:177.)s]

Sanity Checking DataLoader 0:   0%|                                                                                                                                                                                                                       | 0/2 [00:00<?, ?it/s]
/home/tim/anaconda3/envs/JetNN/lib/python3.11/site-packages/torch/nn/functional.py:4999: UserWarning: Support for mismatched key_padding_mask and attn_mask is deprecated. Use same type for both instead.
  warnings.warn(
/home/tim/anaconda3/envs/JetNN/lib/python3.11/site-packages/torch/nn/modules/activation.py:1160: UserWarning: Converting mask without torch.bool dtype to bool; this will negatively affect performance. Prefer to use a boolean mask directly. (Triggered internally at ../aten/src/ATen/native/transformers/attention.cpp:150.)

Sanity Checking DataLoader 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:09<00:00,  4.54s/it]
val
---------------
loss = 10.97
f1 = 0.0
precision = 0.0
recall = 0.0
chrf = 5.93
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 165300/165300 [00:00<00:00, 378681.89it/s]

Epoch 0:   0%|                                                                                                                                                                                            | 1/11545 [00:22<73:00:29, 22.77s/it, loss=10.8, v_num=gwbe, f1=0.000]
/home/tim/anaconda3/envs/JetNN/lib/python3.11/site-packages/pytorch_lightning/trainer/call.py:48: UserWarning: Detected KeyboardInterrupt, attempting graceful shutdown...
  rank_zero_warn("Detected KeyboardInterrupt, attempting graceful shutdown...")
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10664/10664 [00:00<00:00, 618825.08it/s]
Exception ignored in: <function _releaseLock at 0x7f6580986660>                                                                                                                                                                                       | 0/10664 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/tim/anaconda3/envs/JetNN/lib/python3.11/logging/__init__.py", line 237, in _releaseLock
    def _releaseLock():

Testing: 0it [00:00, ?it/s]                                                                                                                                                                               | 1/11545 [00:22<73:00:29, 22.77s/it, loss=10.8, v_num=gwbe, f1=0.000]